import * as fs from 'node:fs';
import * as path from 'node:path';
import { parse as parseYaml } from 'yaml';
import type { InstanceObject } from '@cee/models/instance-node.model';

/**
 * A vendored snapshot of the CEDAR artifact corpus — real templates and
 * instances. See `harness/fixtures/README.md` for provenance and refresh
 * instructions.
 *
 * Everything else in this harness generates its own templates, which buys
 * enumerable coverage of the axes CEE branches on. It also means CEE is only
 * ever fed input the CEDAR Model TypeScript Library produced. These fixtures
 * were authored by people and by the CEDAR Template Editor, so they are the
 * only input here that is independent of that library.
 *
 * That independence is the point, and it becomes load-bearing if CEE ever
 * parses templates *with* the library: the generated tests would then have the
 * library on both sides of the comparison, and would agree with themselves
 * regardless of whether either matched the spec. These would still fail.
 *
 * The fixtures live in this repository so every checkout must run the
 * independent corpus. Missing or incomplete fixtures are a hard error: these
 * suites must never become green by silently skipping their oracle.
 */
const CORPUS_ROOT = path.resolve(__dirname, '../fixtures/corpus');
const EXPECTED_TEMPLATE_COUNT = 37;
const EXPECTED_INSTANCE_COUNT = 21;
const EXPECTED_HUBMAP_COUNT = 57;

const requireDirectory = (dir: string, label: string): void => {
  if (!fs.existsSync(dir)) {
    throw new Error(`Required ${label} fixture directory is missing: ${dir}`);
  }
};

const requireCount = (actual: number, expected: number, label: string): void => {
  if (actual !== expected) {
    throw new Error(`Required ${label} fixture set is incomplete: expected ${expected}, found ${actual}`);
  }
};

export interface CorpusArtifact {
  /** Zero-padded case number, e.g. `003`. */
  id: string;
  /** Parsed source JSON, as authored — not regenerated by any library. */
  json: object;
}

/**
 * A corpus *instance*, whose root is narrowed to the node type the deserializer
 * and the quality report take. A template is a different document and keeps the
 * looser `object`, so the two cannot be handed to each other's readers.
 */
export interface CorpusInstance {
  id: string;
  json: InstanceObject;
}

const load = <T extends object = object>(
  kind: 'templates' | 'instances',
  prefix: string,
  expectedCount: number,
): Array<{ id: string; json: T }> => {
  const dir = path.join(CORPUS_ROOT, kind);
  requireDirectory(dir, `numbered corpus ${kind}`);
  const ids = fs.readdirSync(dir).sort();
  requireCount(ids.length, expectedCount, `numbered corpus ${kind}`);
  return ids.map((id) => {
    const file = path.join(dir, id, `${prefix}-${id}.json`);
    if (!fs.existsSync(file)) {
      throw new Error(`Required numbered corpus fixture is missing: ${file}`);
    }
    return { id, json: JSON.parse(fs.readFileSync(file, 'utf8')) };
  });
};

export const corpusTemplates = (): CorpusArtifact[] => load('templates', 'template', EXPECTED_TEMPLATE_COUNT);

/**
 * The same 37 templates, as YAML.
 *
 * The corpus ships each case in both serialisations. That is what makes it
 * possible to ask whether CEE understands a template or merely understands its
 * JSON — see `format-independence.spec.ts`.
 */
export const corpusTemplatesYaml = (): CorpusArtifact[] => {
  const dir = path.join(CORPUS_ROOT, 'templates');
  requireDirectory(dir, 'numbered corpus templates');
  const ids = fs.readdirSync(dir).sort();
  requireCount(ids.length, EXPECTED_TEMPLATE_COUNT, 'numbered corpus YAML templates');
  return ids.map((id) => {
    const file = path.join(dir, id, `template-${id}.yaml`);
    if (!fs.existsSync(file)) {
      throw new Error(`Required numbered corpus fixture is missing: ${file}`);
    }
    return { id, json: parseYaml(fs.readFileSync(file, 'utf8')) as object };
  });
};
export const corpusInstances = (): CorpusInstance[] =>
  load<InstanceObject>('instances', 'instance', EXPECTED_INSTANCE_COUNT);

/**
 * A vendored snapshot of the HuBMAP production templates originally shipped
 * with `cedar-artifact-library`.
 *
 * Bigger and messier than the numbered test fixtures — these are real
 * templates people authored and used, with deep element nesting, controlled
 * terms and the long tail of `_ui` metadata a generator never emits. They are
 * normalized JSON renderings of the YAML corpus in the same repo.
 */
const HUBMAP_ROOT = path.resolve(__dirname, '../fixtures/hubmap');

export const hubmapTemplates = (): CorpusArtifact[] => {
  requireDirectory(HUBMAP_ROOT, 'HuBMAP corpus');
  const files = fs
    .readdirSync(HUBMAP_ROOT)
    .filter((f) => f.endsWith('.json'))
    .sort();
  requireCount(files.length, EXPECTED_HUBMAP_COUNT, 'HuBMAP corpus');
  return files.map((f) => ({
    id: f.replace(/\.json$/, ''),
    json: JSON.parse(fs.readFileSync(path.join(HUBMAP_ROOT, f), 'utf8')),
  }));
};

/**
 * A stable, comparable summary of a parsed component tree.
 *
 * Deliberately not a snapshot of the whole representation: that carries object
 * identity, cursors and back-references, so it would churn on changes that mean
 * nothing. This captures what a reader of the form would notice — structure,
 * types, cardinality, constraints — which is what has to survive a change of
 * parsing implementation.
 */
export const describeTree = (node: any, depth = 0): string[] => {
  const lines: string[] = [];
  const indent = '  '.repeat(depth);
  const children = node?.children ?? [];
  for (const child of children) {
    const bits: string[] = [`${indent}${child.name}`];
    const inputType = child.basicInfo?.inputType;
    if (inputType) bits.push(`type=${inputType}`);
    bits.push(child.isMulti?.() ? 'multi' : 'single');
    if (child.hidden) bits.push('hidden');
    if (child.valueInfo?.requiredValue) bits.push('required');
    if (child.multiInfo?.minItems != null) bits.push(`min=${child.multiInfo.minItems}`);
    if (child.multiInfo?.maxItems != null) bits.push(`max=${child.multiInfo.maxItems}`);
    if (child.valueInfo?.minLength != null) bits.push(`minLen=${child.valueInfo.minLength}`);
    if (child.valueInfo?.maxLength != null) bits.push(`maxLen=${child.valueInfo.maxLength}`);
    if (child.numberInfo?.numberType) bits.push(`num=${child.numberInfo.numberType}`);
    if (child.valueInfo?.temporalType) bits.push(`temporal=${child.valueInfo.temporalType}`);
    if (child.basicInfo?.temporalGranularity) bits.push(`gran=${child.basicInfo.temporalGranularity}`);
    if (child.choiceInfo?.choices?.length) bits.push(`choices=${child.choiceInfo.choices.length}`);
    // `multipleChoice` reaches the screen for list fields and nowhere else —
    // `cedar-component-renderer` routes only `InputType.list` to the select
    // widget, which binds it to `multiple`. Recorded here because it decides
    // whether the user can pick one option or several, and without it a change
    // that flipped every select in the corpus would leave no trace.
    if (inputType === 'list') bits.push(child.choiceInfo?.multipleChoice ? 'choice=multi' : 'choice=single');
    for (const kind of ['ontologies', 'classes', 'branches', 'valueSets']) {
      const n = child.controlledInfo?.[kind]?.length;
      if (n) bits.push(`${kind}=${n}`);
    }
    if (child.linkedStaticFieldComponent) bits.push('hasLinkedStatic');
    lines.push(bits.join(' '));
    lines.push(...describeTree(child, depth + 1));
  }
  return lines;
};
