import * as fs from 'node:fs';
import * as path from 'node:path';
import { parse as parseYaml } from 'yaml';

/**
 * The shared CEDAR artifact corpus — real templates and instances.
 *
 * Everything else in this harness generates its own templates, which buys
 * enumerable coverage of the axes CEE branches on. It also means CEE is only
 * ever fed input the CEDAR Model TypeScript Library produced. These fixtures
 * were authored by people and by the CEDAR Template Editor, so they are the
 * only input here that is independent of that library.
 *
 * That independence is the point, and it becomes load-bearing if CEE ever
 * parses templates *with* the library: the generated tests would then have the
 * library on both sides of the comparison, and would agree with themselves
 * regardless of whether either matched the spec. These would still fail.
 *
 * The corpus lives on `cedar-test-artifacts`' **develop** branch — `main`
 * carries only a README. If it is missing, these suites skip rather than fail,
 * so a checkout without it is merely less covered, not broken.
 */
const CORPUS_ROOT = path.resolve(__dirname, '../../../cedar-test-artifacts/artifacts');

export const corpusAvailable = (): boolean => fs.existsSync(CORPUS_ROOT);

export interface CorpusArtifact {
  /** Zero-padded case number, e.g. `003`. */
  id: string;
  /** Parsed source JSON, as authored — not regenerated by any library. */
  json: object;
}

const load = (kind: 'templates' | 'instances', prefix: string): CorpusArtifact[] => {
  const dir = path.join(CORPUS_ROOT, kind);
  if (!fs.existsSync(dir)) {
    return [];
  }
  return fs
    .readdirSync(dir)
    .sort()
    .flatMap((id) => {
      const file = path.join(dir, id, `${prefix}-${id}.json`);
      if (!fs.existsSync(file)) {
        return [];
      }
      return [{ id, json: JSON.parse(fs.readFileSync(file, 'utf8')) }];
    });
};

export const corpusTemplates = (): CorpusArtifact[] => load('templates', 'template');

/**
 * The same 37 templates, as YAML.
 *
 * The corpus ships each case in both serialisations. That is what makes it
 * possible to ask whether CEE understands a template or merely understands its
 * JSON — see `format-independence.spec.ts`.
 */
export const corpusTemplatesYaml = (): CorpusArtifact[] => {
  const dir = path.join(CORPUS_ROOT, 'templates');
  if (!fs.existsSync(dir)) {
    return [];
  }
  return fs
    .readdirSync(dir)
    .sort()
    .flatMap((id) => {
      const file = path.join(dir, id, `template-${id}.yaml`);
      if (!fs.existsSync(file)) {
        return [];
      }
      return [{ id, json: parseYaml(fs.readFileSync(file, 'utf8')) as object }];
    });
};
export const corpusInstances = (): CorpusArtifact[] => load('instances', 'instance');

/**
 * The HuBMAP production templates, as shipped with `cedar-artifact-library`.
 *
 * Bigger and messier than the numbered test fixtures — these are real
 * templates people authored and used, with deep element nesting, controlled
 * terms and the long tail of `_ui` metadata a generator never emits. They are
 * normalized JSON renderings of the YAML corpus in the same repo.
 */
const HUBMAP_ROOT = path.resolve(__dirname, '../../../cedar-artifact-library/src/test/resources/templates-json');

export const hubmapAvailable = (): boolean => fs.existsSync(HUBMAP_ROOT);

export const hubmapTemplates = (): CorpusArtifact[] => {
  if (!hubmapAvailable()) {
    return [];
  }
  return fs
    .readdirSync(HUBMAP_ROOT)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((f) => ({
      id: f.replace(/\.json$/, ''),
      json: JSON.parse(fs.readFileSync(path.join(HUBMAP_ROOT, f), 'utf8')),
    }));
};

/**
 * A stable, comparable summary of a parsed component tree.
 *
 * Deliberately not a snapshot of the whole representation: that carries object
 * identity, cursors and back-references, so it would churn on changes that mean
 * nothing. This captures what a reader of the form would notice — structure,
 * types, cardinality, constraints — which is what has to survive a change of
 * parsing implementation.
 */
export const describeTree = (node: any, depth = 0): string[] => {
  const lines: string[] = [];
  const indent = '  '.repeat(depth);
  const children = node?.children ?? [];
  for (const child of children) {
    const bits: string[] = [`${indent}${child.name}`];
    const inputType = child.basicInfo?.inputType;
    if (inputType) bits.push(`type=${inputType}`);
    bits.push(child.isMulti?.() ? 'multi' : 'single');
    if (child.hidden) bits.push('hidden');
    if (child.valueInfo?.requiredValue) bits.push('required');
    if (child.multiInfo?.minItems != null) bits.push(`min=${child.multiInfo.minItems}`);
    if (child.multiInfo?.maxItems != null) bits.push(`max=${child.multiInfo.maxItems}`);
    if (child.valueInfo?.minLength != null) bits.push(`minLen=${child.valueInfo.minLength}`);
    if (child.valueInfo?.maxLength != null) bits.push(`maxLen=${child.valueInfo.maxLength}`);
    if (child.numberInfo?.numberType) bits.push(`num=${child.numberInfo.numberType}`);
    if (child.valueInfo?.temporalType) bits.push(`temporal=${child.valueInfo.temporalType}`);
    if (child.basicInfo?.temporalGranularity) bits.push(`gran=${child.basicInfo.temporalGranularity}`);
    if (child.choiceInfo?.choices?.length) bits.push(`choices=${child.choiceInfo.choices.length}`);
    // `multipleChoice` reaches the screen for list fields and nowhere else —
    // `cedar-component-renderer` routes only `InputType.list` to the select
    // widget, which binds it to `multiple`. Recorded here because it decides
    // whether the user can pick one option or several, and without it a change
    // that flipped every select in the corpus would leave no trace.
    if (inputType === 'list') bits.push(child.choiceInfo?.multipleChoice ? 'choice=multi' : 'choice=single');
    for (const kind of ['ontologies', 'classes', 'branches', 'valueSets']) {
      const n = child.controlledInfo?.[kind]?.length;
      if (n) bits.push(`${kind}=${n}`);
    }
    if (child.linkedStaticFieldComponent) bits.push('hasLinkedStatic');
    lines.push(bits.join(' '));
    lines.push(...describeTree(child, depth + 1));
  }
  return lines;
};
