export class InputType {
  static numeric = 'numeric';
  static text = 'textfield';
  static textarea = 'textarea';
  static richText = 'richtext';
  static controlled = 'controlled';
  static email = 'email';
  static link = 'link';
  static orcid = 'ext-orcid';
  static ror = 'ext-ror';
  static phoneNumber = 'phone-number';
  static list = 'list';
  static checkbox = 'checkbox';
  static radio = 'radio';
  static temporal = 'temporal';
  static image = 'image';
  static youtube = 'youtube';
  static sectionBreak = 'section-break';
  static pageBreak = 'page-break';
  static attributeValue = 'attribute-value';
}
